name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the action on pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger on PRs to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies (if any)
      run: |
        npm install

    - name: Build the project (if any build process exists)
      run: |
        # For a static site, you likely won't have a build step, so this can be omitted.
        # Example for projects using a static site generator (like Jekyll or Hugo)
        # npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # The directory to publish, set to root for simple static files
        target_branch: gh-pages  # Deploy to the gh-pages branch
